<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Lirik</name>
   <tag></tag>
   <elementGuidId>3bda1acf-cfa9-48eb-93f4-165912b3aa0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-3-content']/ul/li[2]/ul/li[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ce65ad0-53c0-458f-81d6-393306a2b609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-navigation-item__label</value>
      <webElementGuid>262f4e9c-c08c-4ad2-bc9c-00ac158bb981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lirik</value>
      <webElementGuid>5941ce72-5801-4fc4-ae84-59a69465e3dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-3-content&quot;)/ul[@class=&quot;wp-block-navigation__container has-background is-responsive items-justified-center wp-block-navigation&quot;]/li[@class=&quot;wp-block-navigation-item has-child open-on-hover-click wp-block-navigation-submenu&quot;]/ul[@class=&quot;wp-block-navigation__submenu-container wp-block-navigation-submenu&quot;]/li[@class=&quot;wp-block-navigation-item wp-block-navigation-link&quot;]/a[@class=&quot;wp-block-navigation-item__content&quot;]/span[@class=&quot;wp-block-navigation-item__label&quot;]</value>
      <webElementGuid>08be9f45-7286-4adb-9301-421fc7f1d0f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-3-content']/ul/li[2]/ul/li[2]/a/span</value>
      <webElementGuid>d36db636-6327-4a44-bfa2-7b7ed467e359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>b8e9c95a-08ff-44a5-86e5-4f6fb27c5d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Lirik' or . = 'Lirik')]</value>
      <webElementGuid>4d041bab-10ca-4f65-880d-02d509ada4bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
