<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Diskografi</name>
   <tag></tag>
   <elementGuidId>65c21403-1ae7-4f4d-bbc7-edb29e08df9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-3-content']/ul/li[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4c25cb0a-d2a5-4441-a7d1-d69baa6155e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-navigation-item__content</value>
      <webElementGuid>cd16c712-5e37-4fff-becb-2ddbdc4b1b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://berandalanjenius.com/#diskografi</value>
      <webElementGuid>a1ceda08-3ef3-4748-87aa-e1c105607b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Diskografi</value>
      <webElementGuid>41edfd7e-2d53-46fc-8ccf-529dbb72456b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-3-content&quot;)/ul[@class=&quot;wp-block-navigation__container has-background is-responsive items-justified-center wp-block-navigation&quot;]/li[@class=&quot;wp-block-navigation-item has-child open-on-hover-click wp-block-navigation-submenu&quot;]/ul[@class=&quot;wp-block-navigation__submenu-container wp-block-navigation-submenu&quot;]/li[@class=&quot;wp-block-navigation-item wp-block-navigation-link&quot;]/a[@class=&quot;wp-block-navigation-item__content&quot;]</value>
      <webElementGuid>3fa3ddf7-6340-4f36-a0d0-262bb48fa36b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-3-content']/ul/li[2]/ul/li/a</value>
      <webElementGuid>52c911d2-758b-4fff-b894-feae48dadb1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://berandalanjenius.com/#diskografi')]</value>
      <webElementGuid>b47b99c9-4853-453e-af47-fcead8f8a6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>242f2471-ea36-4a89-9ab9-5e0d5c2eacfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://berandalanjenius.com/#diskografi' and (text() = 'Diskografi' or . = 'Diskografi')]</value>
      <webElementGuid>8642dc81-1d7e-4916-b7ac-076f20cead5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
