<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Danau Galau (Versi Akustik)</name>
   <tag></tag>
   <elementGuidId>2081976d-e9a4-4e00-aa95-ebd360b99dd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ol:nth-of-type(3) > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='wp--skip-link--target']/div[3]/ol[3]/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>06732a4d-fd49-468f-b414-95177b63cbcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://berandalanjenius.com/lirik-danau-galau/</value>
      <webElementGuid>4860feec-3933-4768-b59d-7fb0e35c8aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Danau Galau (Versi Akustik)</value>
      <webElementGuid>3d4aef8e-8490-4b3c-bff1-58a7991df459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wp--skip-link--target&quot;)/div[@class=&quot;entry-content wp-block-post-content is-layout-constrained wp-block-post-content-is-layout-constrained&quot;]/ol[3]/li[1]/a[1]</value>
      <webElementGuid>2f043ed2-ac24-40b1-b62f-4069e4b0f545</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='wp--skip-link--target']/div[3]/ol[3]/li/a</value>
      <webElementGuid>cd18f223-7173-4005-99ec-b4a4b78d5d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Danau Galau (Versi Akustik)')]</value>
      <webElementGuid>866f8efa-3eb7-41ab-9de1-03fefd81ab7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://berandalanjenius.com/lirik-danau-galau/')]</value>
      <webElementGuid>523a18d8-5956-4b46-b1c5-7fb49b76f484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol[3]/li/a</value>
      <webElementGuid>60449624-3c0a-4e6e-9b38-97cfce6a5b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://berandalanjenius.com/lirik-danau-galau/' and (text() = 'Danau Galau (Versi Akustik)' or . = 'Danau Galau (Versi Akustik)')]</value>
      <webElementGuid>94c2369a-215b-463c-b26f-02791888ef91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
