<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Danau Galau</name>
   <tag></tag>
   <elementGuidId>1f8f8080-fae5-48fa-a211-c2a7f03e9c99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(9) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='wp--skip-link--target']/div[3]/ol[4]/li[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d3c744d8-c910-4a7c-a988-bf91eb22d6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://berandalanjenius.com/lirik-danau-galau/</value>
      <webElementGuid>50826100-0673-43e3-b5ce-b9f7da18a0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Danau Galau</value>
      <webElementGuid>8b3b0159-b43d-499d-8e74-1f29ee11c966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wp--skip-link--target&quot;)/div[@class=&quot;entry-content wp-block-post-content is-layout-constrained wp-block-post-content-is-layout-constrained&quot;]/ol[4]/li[9]/a[1]</value>
      <webElementGuid>cdb464ba-6c5e-4959-8ec9-7982c9b92fe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='wp--skip-link--target']/div[3]/ol[4]/li[9]/a</value>
      <webElementGuid>539f3e80-b0ef-423b-a8d1-0f40503a7bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Danau Galau')])[3]</value>
      <webElementGuid>d504585b-48dd-4a0f-bab2-7ce1a65e0fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://berandalanjenius.com/lirik-danau-galau/')])[3]</value>
      <webElementGuid>3950d6f0-d96e-4a76-a1b6-1b2bcd7f027c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a</value>
      <webElementGuid>1ec5342a-5204-4b84-8a1f-2c2e476542dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://berandalanjenius.com/lirik-danau-galau/' and (text() = 'Danau Galau' or . = 'Danau Galau')]</value>
      <webElementGuid>7dedb3e7-ca2d-49c8-8ae5-2a530385b05d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
