<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Danau Galau (2020 Demo)</name>
   <tag></tag>
   <elementGuidId>08e6df84-7a90-49e5-a81f-8d5a12909ed8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ol:nth-of-type(3) > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='wp--skip-link--target']/div[3]/ol[3]/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0aa22103-5f73-4404-af76-c08e5e8fe91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://berandalanjenius.com/lirik-danau-galau/</value>
      <webElementGuid>d9c769cc-6684-4ccf-b7c2-dc4b6895e1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Danau Galau (2020 Demo)</value>
      <webElementGuid>6989a0e9-d22f-44b2-89f6-e3a6eb6f0eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wp--skip-link--target&quot;)/div[@class=&quot;entry-content wp-block-post-content is-layout-constrained wp-block-post-content-is-layout-constrained&quot;]/ol[3]/li[2]/a[1]</value>
      <webElementGuid>a8dd34fd-dfc5-4ad6-9914-ef2025e37ce3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='wp--skip-link--target']/div[3]/ol[3]/li[2]/a</value>
      <webElementGuid>55a2edb0-fbdc-4eca-897f-c5469c648325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Danau Galau (2020 Demo)')]</value>
      <webElementGuid>ff5b2282-386a-42ac-a81e-8702b40b7777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://berandalanjenius.com/lirik-danau-galau/')])[2]</value>
      <webElementGuid>c75ad1a9-8dbe-4f8d-9957-1bd9c5a790ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol[3]/li[2]/a</value>
      <webElementGuid>df2d7218-365c-4c03-9605-a24d7d6453fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://berandalanjenius.com/lirik-danau-galau/' and (text() = 'Danau Galau (2020 Demo)' or . = 'Danau Galau (2020 Demo)')]</value>
      <webElementGuid>f16d7341-5e45-4807-83c1-c84335167938</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
