<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Perpisahan</name>
   <tag></tag>
   <elementGuidId>a33695cb-a045-4c2f-b45b-b430ddc3fafe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(15) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='wp--skip-link--target']/div[3]/ol[4]/li[15]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9a6e5cb5-93e5-44bf-a5ea-b0b9e8fd607e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://berandalanjenius.com/lirik-perpisahan/</value>
      <webElementGuid>370878be-8105-474d-b6e9-27b45bcf3a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Perpisahan</value>
      <webElementGuid>2d68d22c-7716-4d62-a36f-55df5ad02949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wp--skip-link--target&quot;)/div[@class=&quot;entry-content wp-block-post-content is-layout-constrained wp-block-post-content-is-layout-constrained&quot;]/ol[4]/li[15]/a[1]</value>
      <webElementGuid>eb16e30b-f559-45ff-9d04-3728d12cbb6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='wp--skip-link--target']/div[3]/ol[4]/li[15]/a</value>
      <webElementGuid>cfb0b693-5326-4081-a035-312616398975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Perpisahan')]</value>
      <webElementGuid>890132f4-e3be-4be4-a4a2-b49f3dbf2aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://berandalanjenius.com/lirik-perpisahan/')]</value>
      <webElementGuid>c58cf10a-7340-4f64-8963-4e35a60d3890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[15]/a</value>
      <webElementGuid>8123693c-728c-4e6d-a694-fdc879ff4016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://berandalanjenius.com/lirik-perpisahan/' and (text() = 'Perpisahan' or . = 'Perpisahan')]</value>
      <webElementGuid>ba865f29-f6ca-4b40-8e56-404f4bce1343</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
