<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tua  Bosan</name>
   <tag></tag>
   <elementGuidId>1185227b-3719-4d2e-81d2-e3bc0f8b5c45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ol:nth-of-type(6) > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='wp--skip-link--target']/div[3]/ol[6]/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0612ace-c317-40de-b353-3472241fd84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://berandalanjenius.com/lirik-tua-bosan/</value>
      <webElementGuid>d5e5ca56-942d-4e4d-b253-57b3a780718f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tua &amp; Bosan</value>
      <webElementGuid>57fdc22c-faed-4e4a-9136-b6a71e3995df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wp--skip-link--target&quot;)/div[@class=&quot;entry-content wp-block-post-content is-layout-constrained wp-block-post-content-is-layout-constrained&quot;]/ol[6]/li[1]/a[1]</value>
      <webElementGuid>77c86307-0454-446d-b5b3-fb462d6b9205</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='wp--skip-link--target']/div[3]/ol[6]/li/a</value>
      <webElementGuid>5f9488e6-218d-4223-acc9-93a0b7e3de22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tua &amp; Bosan')]</value>
      <webElementGuid>b55f3520-d4c5-4f62-aaea-da2141df939a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://berandalanjenius.com/lirik-tua-bosan/')]</value>
      <webElementGuid>6daf1ccc-bb33-43c4-bc92-c5ddb9dcdfc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol[6]/li/a</value>
      <webElementGuid>3ec4f8a3-6ae5-4afe-8baa-8ab05c394ff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://berandalanjenius.com/lirik-tua-bosan/' and (text() = 'Tua &amp; Bosan' or . = 'Tua &amp; Bosan')]</value>
      <webElementGuid>910a07c8-d80f-473b-a0b4-9ecffebfee65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
