<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Musik</name>
   <tag></tag>
   <elementGuidId>838d4ed7-44ab-4b80-b3f8-0786b3187b66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-3-content']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>80c46f19-e1d4-4b2f-abe8-de1abc96041f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-navigation-item__content</value>
      <webElementGuid>32f807c7-1162-4c07-9b16-2f94a48707d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>e32102ee-b4f2-4b2d-95a2-6834063401f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Musik</value>
      <webElementGuid>cde26817-e9e1-4a1e-932a-42d1a9796cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-3-content&quot;)/ul[@class=&quot;wp-block-navigation__container has-background is-responsive items-justified-center wp-block-navigation&quot;]/li[@class=&quot;wp-block-navigation-item has-child open-on-hover-click wp-block-navigation-submenu&quot;]/a[@class=&quot;wp-block-navigation-item__content&quot;]</value>
      <webElementGuid>f1733e12-5cf7-418d-9a19-f575a806a6cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-3-content']/ul/li[2]/a</value>
      <webElementGuid>30fddc04-6696-4e57-8403-ade4bd04d14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Musik')]</value>
      <webElementGuid>e7ab8a8b-3987-4379-ba9b-34b15a0e467d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>f6c09163-8cfd-4641-acf2-b588f1640a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>cc1b2407-0f5d-42aa-a074-2bb9675120d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Musik' or . = 'Musik')]</value>
      <webElementGuid>1f1ab152-4461-487a-8699-e3d25cad8184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
