<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Gw bakalan balas pesan lo secepat mungkin</name>
   <tag></tag>
   <elementGuidId>6baca792-e647-415e-9b6f-5bec7d799f7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='schedule-a-visit']/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>b1e56234-3d55-4102-b202-1a82a6e79909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gw bakalan balas pesan lo secepat mungkin.</value>
      <webElementGuid>a934f82c-a8aa-47ef-8c87-edaf0b18c594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;schedule-a-visit&quot;)/strong[1]</value>
      <webElementGuid>ff7a4a4c-7751-4114-86f5-86d88616b2b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h2[@id='schedule-a-visit']/strong</value>
      <webElementGuid>14b1502d-1c3c-45c8-949f-36768980acb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>f0aa6641-9461-42a7-a39e-6f22b8ab52f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Gw bakalan balas pesan lo secepat mungkin.' or . = 'Gw bakalan balas pesan lo secepat mungkin.')]</value>
      <webElementGuid>95a5a36d-09e4-446e-ac84-ff2cbbd48da7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
