<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Lirik</name>
   <tag></tag>
   <elementGuidId>3d9c8024-83d5-4643-a930-06518ae465f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-3-content']/ul/li[2]/ul/li[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3dfc2262-ed08-41b2-b720-b3ae5bd56384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-navigation-item__label</value>
      <webElementGuid>486b51c2-7abc-4468-88aa-3df1593e0efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lirik</value>
      <webElementGuid>28e15303-1ed9-48c7-b008-2f5296f88098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-3-content&quot;)/ul[@class=&quot;wp-block-navigation__container has-background is-responsive items-justified-center wp-block-navigation&quot;]/li[@class=&quot;wp-block-navigation-item has-child open-on-hover-click wp-block-navigation-submenu&quot;]/ul[@class=&quot;wp-block-navigation__submenu-container wp-block-navigation-submenu&quot;]/li[@class=&quot;wp-block-navigation-item wp-block-navigation-link&quot;]/a[@class=&quot;wp-block-navigation-item__content&quot;]/span[@class=&quot;wp-block-navigation-item__label&quot;]</value>
      <webElementGuid>45dbe6bd-1d2e-4c28-be37-a81933ef4c7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-3-content']/ul/li[2]/ul/li[2]/a/span</value>
      <webElementGuid>d11dc909-0219-490e-97dd-cd24a0f6f7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>f5d235d5-c846-4ef6-995a-75582cae0ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Lirik' or . = 'Lirik')]</value>
      <webElementGuid>3a2bb58e-2bed-4307-aae9-8995fbde69b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
