<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Diskografi</name>
   <tag></tag>
   <elementGuidId>8e615e03-ea99-4708-99ec-cfc93683d358</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-3-content']/ul/li[2]/ul/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c2468937-c068-4f64-9186-38952f0167f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-navigation-item__label</value>
      <webElementGuid>92e13636-ea57-42a8-8f65-9fae2bcdb767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Diskografi</value>
      <webElementGuid>8707f51e-614f-49a4-b9c5-c5dfcf27a8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-3-content&quot;)/ul[@class=&quot;wp-block-navigation__container has-background is-responsive items-justified-center wp-block-navigation&quot;]/li[@class=&quot;wp-block-navigation-item has-child open-on-hover-click wp-block-navigation-submenu&quot;]/ul[@class=&quot;wp-block-navigation__submenu-container wp-block-navigation-submenu&quot;]/li[@class=&quot;wp-block-navigation-item wp-block-navigation-link&quot;]/a[@class=&quot;wp-block-navigation-item__content&quot;]/span[@class=&quot;wp-block-navigation-item__label&quot;]</value>
      <webElementGuid>34140a91-71f3-4491-bc19-ac6823ad92d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-3-content']/ul/li[2]/ul/li/a/span</value>
      <webElementGuid>0d792a38-c544-431a-b240-87bb4b6c95c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a/span</value>
      <webElementGuid>2960b20d-e4de-498b-a79f-6f07c2515117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Diskografi' or . = 'Diskografi')]</value>
      <webElementGuid>2d1b8b80-2e7f-4ce6-a6c5-93108344a599</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
